### ISSUE TITLE
Update to PM4.

### ISSUE THREAD

**Issue by EPT8TPE** [EPT8TPE/Prisons#16]
I am currently rather busy, if anyone would like to update this plugin to PM4, that would be heavily appreciated, if it's not done, I will eventually get round to doing it, open a pull request if you choose to do so, thank you!

**Comment by EPT8TPE** [comment]
I have updated it as best I can on the PM4 branch but until an economy and permission manager plugin are officially released on poggit I can not continue.

**Comment by galaxytwenty** [comment]
i cant find Minereset for PM4... you said is an dependency ?.

**Comment by EPT8TPE** [comment]
Completed
